import type { Brand } from "./types";

export const brands: Brand[] = [
  {
    id: "maison-verane",
    slug: "maison-verane",
    name: "Maison Vérane",
    tagline: "Parisian tailoring, quietly radical.",
    origin: "Paris, France",
    since: 1988,
    hero: "verane-hero",
    logotype: "VÉRANE",
    bio: "Founded in an atelier near the Palais Royal, Maison Vérane reinterprets French tailoring with an architect's restraint. Each piece is cut to move.",
    featured: true,
    collections: ["Soft Tailoring", "Evening Essentials", "Archive Reissue"],
    sustainability: "Cupro linings, traceable Italian wool, and a repair atelier in Paris.",
    videoSeed: "verane-hero",
    relatedBrandIds: ["sanso", "belrose", "atelier-norde"],
  },
  {
    id: "atelier-norde",
    slug: "atelier-norde",
    name: "Atelier Nordé",
    tagline: "Scandinavian minimalism, made to last.",
    origin: "Copenhagen, Denmark",
    since: 2011,
    hero: "norde-hero",
    logotype: "NORDÉ",
    bio: "Atelier Nordé believes in fewer, better things. Natural fibres, honest construction, and a palette drawn from the northern light.",
    featured: true,
    collections: ["Everyday Knit", "Organic Poplin", "Lifetime Repair"],
    sustainability: "GOTS cotton, free lifetime repairs, solar-powered atelier.",
    videoSeed: "norde-hero",
    relatedBrandIds: ["sanso", "hana-mori", "maison-verane"],
  },
  {
    id: "sanso",
    slug: "sanso",
    name: "SÀNSO",
    tagline: "The art of the essential.",
    origin: "Milan, Italy",
    since: 2016,
    hero: "sanso-hero",
    logotype: "SÀNSO",
    bio: "SÀNSO strips fashion to its essence — clean lines, elevated materials, and a devotion to the perfect proportion.",
    featured: true,
    collections: ["Essentials", "Leather Atelier", "Quiet Luxury"],
    sustainability: "Vegetable-tanned leather and recycled vermeil jewellery.",
    videoSeed: "sanso-hero",
    relatedBrandIds: ["maison-verane", "solene", "atelier-norde"],
  },
  {
    id: "okoro",
    slug: "okoro",
    name: "Okoro",
    tagline: "Heritage craft, future form.",
    origin: "Lagos, Nigeria",
    since: 2019,
    hero: "okoro-hero",
    logotype: "OKORO",
    bio: "Okoro fuses West African textile heritage with a sculptural, contemporary silhouette. Every collection tells a story of place.",
    featured: true,
    collections: ["Adire Edit", "Aso-Oke Evening", "Heritage Weave"],
    sustainability: "Fair-wage artisan partnerships; each maker credited by name.",
    videoSeed: "okoro-hero",
    relatedBrandIds: ["hana-mori", "belrose", "solene"],
  },
  {
    id: "hana-mori",
    slug: "hana-mori",
    name: "Hana Mori",
    tagline: "Wabi-sabi, in wearable form.",
    origin: "Kyoto, Japan",
    since: 2007,
    hero: "hana-hero",
    logotype: "花森",
    bio: "Hana Mori draws on Japanese notions of imperfection and impermanence, crafting garments that age gracefully alongside their wearer.",
    featured: true,
    collections: ["Boro Stories", "Indigo Work", "Sashiko"],
    sustainability: "Upcycled indigo cotton and hand sashiko mending.",
    videoSeed: "hana-hero",
    relatedBrandIds: ["okoro", "atelier-norde", "kestrel"],
  },
  {
    id: "belrose",
    slug: "belrose",
    name: "Belrose",
    tagline: "Modern romance.",
    origin: "London, United Kingdom",
    since: 2014,
    hero: "belrose-hero",
    logotype: "BELROSE",
    bio: "Belrose is British romanticism reimagined — fluid dresses, soft tailoring, and a signature blush that has become a house code.",
    featured: false,
    collections: ["Evening Slip", "Garden Party", "Soft Shoulder"],
    sustainability: "Sandwashed silk from certified mills; low-impact dyes.",
    videoSeed: "belrose-hero",
    relatedBrandIds: ["maison-verane", "solene", "okoro"],
  },
  {
    id: "kestrel",
    slug: "kestrel",
    name: "Kestrel & Co.",
    tagline: "Utility, elevated.",
    origin: "New York, USA",
    since: 2013,
    hero: "kestrel-hero",
    logotype: "KESTREL",
    bio: "Kestrel & Co. takes the language of American workwear and refines it with luxury materials and an editorial eye.",
    featured: false,
    collections: ["Field Utility", "City Boot", "Selvedge"],
    sustainability: "Traceable denim and chrome-free suede finishing.",
    videoSeed: "kestrel-hero",
    relatedBrandIds: ["hana-mori", "atelier-norde", "sanso"],
  },
  {
    id: "solene",
    slug: "solene",
    name: "Solène",
    tagline: "Sun-warmed luxury.",
    origin: "Côte d'Azur, France",
    since: 2018,
    hero: "solene-hero",
    logotype: "SOLÈNE",
    bio: "Solène captures the ease of the Riviera — resort dressing, linen in every weight, and a golden-hour palette.",
    featured: false,
    collections: ["Riviera Linen", "Golden Hour", "Resort Escape"],
    sustainability: "European linen and garment-dyed finishes with low water use.",
    videoSeed: "solene-hero",
    relatedBrandIds: ["belrose", "sanso", "maison-verane"],
  },
];

export function getBrand(id: string) {
  return brands.find((b) => b.id === id || b.slug === id);
}

export function relatedBrands(brandId: string) {
  const brand = getBrand(brandId);
  if (!brand?.relatedBrandIds?.length) {
    return brands.filter((b) => b.id !== brandId).slice(0, 4);
  }
  return brand.relatedBrandIds.map((id) => getBrand(id)).filter(Boolean) as Brand[];
}
