import type { JournalArticle } from "./types";

export const journalCategories = [
  "Designer Interview",
  "Italian Craftsmanship",
  "Seasonal Trends",
  "Style Guide",
  "Travel & Fashion",
  "Sustainability",
  "Runway Coverage",
  "Celebrity Styling",
  "Product Care",
] as const;

export const journal: JournalArticle[] = [
  {
    slug: "the-new-tailoring",
    title: "The New Tailoring: Softness as Strength",
    dek: "How a generation of designers is rewriting the rules of the suit — trading rigidity for fluid, lived-in power.",
    category: "Style Guide",
    author: "Camille Auclair",
    readTime: 6,
    date: "2026-07-18",
    hero: "journal-tailoring",
    featured: true,
    brandId: "maison-verane",
    productIds: ["sculpted-wool-blazer", "pleated-wide-leg-trouser", "merino-crewneck-sweater"],
    body: [
      "For decades, tailoring meant armour. Structured shoulders, canvassed chests, a silhouette engineered to impose. But a quiet revolution has been unfolding in the ateliers of Paris and Milan — one that prizes ease over authority.",
      "At Maison Vérane, creative director Léa Vérane describes the shift as 'the difference between a suit that wears you and one you wear.' Her Sculpted Wool Blazer, cut with a softly rounded shoulder and unlined back, moves with the body rather than against it.",
      "The result is a new kind of power dressing — one that whispers rather than shouts. Pair a fluid blazer with wide-leg trousers and a fine merino crew, and you have a uniform for the modern day that transitions from studio to dinner without a second thought.",
      "This season, we're styling soft tailoring three ways: monochrome and tonal for the boardroom, with denim for the weekend, and over a bias-cut slip for evening. The through-line is always movement.",
    ],
  },
  {
    slug: "okoro-heritage-future",
    title: "Okoro: Where Heritage Meets the Future",
    dek: "In conversation with the Lagos house turning traditional textile craft into a global luxury language.",
    category: "Designer Interview",
    author: "Ada Nwosu",
    readTime: 8,
    date: "2026-07-10",
    hero: "journal-okoro",
    featured: true,
    brandId: "okoro",
    productIds: ["adire-wrap-midi-skirt", "handwoven-aso-oke-clutch"],
    body: [
      "Step into Okoro's Lagos studio and you'll find looms alongside laser cutters, indigo vats beside mood boards. This is a house that refuses to choose between the ancestral and the avant-garde.",
      "'Every piece we make begins with a question: how do we honour the hands that came before us while making something entirely new?' says founder Ifeoma Okoro. The answer, this season, is a wrap skirt in hand-dyed adire — each panel unique, each garment one of a kind.",
      "The house's commitment to artisanal production is not a marketing story; it's the entire business. Weavers and dyers are paid fair wages and credited by name. 'Luxury,' Okoro insists, 'should mean knowing exactly who made your clothes.'",
      "As Okoro expands onto the global stage through Bosiano, that philosophy travels with it — a reminder that the future of fashion may look a great deal like its most rooted past.",
    ],
  },
  {
    slug: "packing-for-the-riviera",
    title: "Packing for the Riviera: A Golden-Hour Edit",
    dek: "Seven pieces from Solène that carry you from beach club to candlelit terrace.",
    category: "Travel & Fashion",
    author: "Marco Bianchi",
    readTime: 5,
    date: "2026-07-02",
    hero: "journal-riviera",
    brandId: "solene",
    productIds: ["riviera-linen-shirt", "poplin-tiered-maxi-dress", "silk-twill-scarf", "minimalist-leather-sneaker"],
    body: [
      "The secret to packing light is a tight palette and fabrics that earn their place. On the Côte d'Azur, that means linen in every weight and a colour story pulled from the sea and the setting sun.",
      "Start with the Riviera Linen Shirt in white — it goes with everything and only looks better crumpled. Layer the Poplin Tiered Maxi for long lunches, and keep a silk scarf on hand for cooler evenings.",
      "Footwear should be minimal: a single pair of leather sneakers will see you through boardwalks and bistros alike. Everything else is sunscreen and good company.",
    ],
  },
  {
    slug: "the-case-for-fewer-better",
    title: "The Case for Fewer, Better Things",
    dek: "Atelier Nordé on why the most sustainable garment is the one you already love.",
    category: "Sustainability",
    author: "Sofie Lund",
    readTime: 7,
    date: "2026-06-24",
    hero: "journal-sustainability",
    brandId: "atelier-norde",
    productIds: ["organic-cotton-oversized-shirt", "merino-crewneck-sweater"],
    body: [
      "The fashion industry's carbon problem will not be solved by recycling alone. It will be solved by buying less — and buying better. That is the founding premise of Atelier Nordé.",
      "'We design garments to be worn hundreds of times, not a handful,' says head designer Sofie Lund. That means GOTS-certified organic cotton, extra-fine merino that resists pilling, and construction that can be repaired rather than replaced.",
      "The house offers free repairs for life on every piece — an economic argument as much as an ethical one. When a garment lasts a decade, the cost-per-wear approaches zero, and the landfill stays empty.",
      "It's a slower way to shop. It's also, we'd argue, the only way forward.",
    ],
  },
  {
    slug: "how-to-build-a-capsule",
    title: "How to Build a Capsule Wardrobe That Actually Works",
    dek: "Twelve pieces, endless outfits. Our editors map the foundation of a wardrobe that lasts.",
    category: "Style Guide",
    author: "Camille Auclair",
    readTime: 9,
    date: "2026-06-15",
    hero: "journal-capsule",
    productIds: [
      "sculpted-wool-blazer",
      "pleated-wide-leg-trouser",
      "organic-cotton-oversized-shirt",
      "structured-leather-tote",
      "minimalist-leather-sneaker",
      "signet-vermeil-ring",
    ],
    body: [
      "A capsule wardrobe isn't about deprivation — it's about intention. The goal is a small collection of pieces that mix effortlessly, in a palette that flatters you and fabrics that endure.",
      "Begin with tailoring: one exceptional blazer and a pair of wide-leg trousers. Add knitwear in three neutral tones, two crisp shirts, and a single perfect white tee. For the base, a bias slip and a pair of selvedge jeans.",
      "Accessories do the heavy lifting. One structured tote, one soft shoulder bag, a pair of minimalist sneakers and one elegant heel. Finish with a signet ring and a silk scarf, and you can dress for almost any occasion.",
      "The magic is in the restraint. When everything works together, getting dressed becomes a pleasure rather than a puzzle.",
    ],
  },
  {
    slug: "the-art-of-the-signet",
    title: "The Art of the Signet Ring",
    dek: "Once a mark of lineage, the signet has become jewellery's most quietly personal statement.",
    category: "Style Guide",
    author: "Jonah Reyes",
    readTime: 4,
    date: "2026-06-04",
    hero: "journal-signet",
    brandId: "sanso",
    productIds: ["signet-vermeil-ring", "twisted-hoop-earrings"],
    body: [
      "The signet ring has carried meaning for millennia — a seal pressed into wax, a family crest, a mark of belonging. Today it endures for a different reason: its quiet, genderless elegance.",
      "SÀNSO's take, in recycled gold vermeil, strips away the heraldry and keeps the form. Worn on the pinky in the traditional manner, or stacked on any finger you like, it reads as considered rather than showy.",
      "It is, in short, the perfect first piece of fine jewellery — and, gift-boxed, a gesture that lasts far longer than the occasion.",
    ],
  },
  {
    slug: "milanese-leather-atelier",
    title: "Inside the Milanese Leather Atelier",
    dek: "How SÀNSO's vegetable-tanned totes are still finished by hand in a workshop outside Milan.",
    category: "Italian Craftsmanship",
    author: "Giulia Conti",
    readTime: 7,
    date: "2026-07-22",
    hero: "about-editorial",
    brandId: "sanso",
    productIds: ["structured-leather-tote", "crescent-shoulder-bag"],
    featured: true,
    body: [
      "In a quiet courtyard outside Milan, artisans still edge, stitch, and burnish each SÀNSO tote by hand. The leather arrives vegetable-tanned — slow, fragrant, and ready to patina.",
      "Nothing here is rushed. Edge paint is applied in thin passes; seams are saddle-stitched for longevity. The result is a bag that softens with you rather than against you.",
      "Italian craftsmanship, for SÀNSO, is not nostalgia — it is the only way to deliver the proportion and hand-feel the house demands.",
    ],
  },
  {
    slug: "autumn-26-trends",
    title: "Autumn 2026: Soft Structure & Earth Metals",
    dek: "The season's key trends — from architectural coats to vermeil accents — shopped from the Bosiano edit.",
    category: "Seasonal Trends",
    author: "Camille Auclair",
    readTime: 5,
    date: "2026-07-25",
    hero: "hero-autumn-campaign",
    productIds: ["architectural-trench-coat", "double-breasted-wool-coat", "sculptural-heeled-mule", "signet-vermeil-ring"],
    body: [
      "Autumn 2026 favours soft structure: coats with clean lines, heels with sculptural heels, and metals that warm rather than flash.",
      "Earth metals — vermeil, brushed brass, muted gold — replace high chrome. Pair them with camel, charcoal, and deep indigo.",
      "The trench returns, stripped of epaulettes. The mule becomes the daytime heel. Knitwear stays fine-gauge and layerable.",
    ],
  },
  {
    slug: "runway-to-reality",
    title: "Runway to Reality: Translating the Shows",
    dek: "How to wear the season's strongest runway ideas without costume.",
    category: "Runway Coverage",
    author: "Jonah Reyes",
    readTime: 6,
    date: "2026-07-14",
    hero: "hero-riviera-film",
    productIds: ["fluid-silk-slip-dress", "architectural-trench-coat", "boro-patchwork-jacket"],
    body: [
      "Runway ideas often fail in real life because they arrive as costumes. The better approach is translation: one silhouette, one texture, one unexpected proportion.",
      "Take the fluid slip — keep the bias cut, soften the drama with a trench. Or borrow boro patchwork as a single layer over clean denim.",
      "Bosiano's edit pulls the wearable core from each show so you can shop the idea, not the theatrics.",
    ],
  },
  {
    slug: "celebrity-quiet-luxury",
    title: "Celebrity Styling: The Quiet Luxury Uniform",
    dek: "How public figures are embracing understated houses — and which Bosiano pieces echo the look.",
    category: "Celebrity Styling",
    author: "Ada Nwosu",
    readTime: 4,
    date: "2026-07-08",
    hero: "look-quiet-luxury",
    productIds: ["sculpted-wool-blazer", "structured-leather-tote", "minimalist-leather-sneaker"],
    body: [
      "The loud logo moment has cooled. What remains is proportion: a strong shoulder, a clean tote, trainers that disappear into the outfit.",
      "Stylists are choosing houses that read expensive without announcing it — soft wool, unbranded leather, monochrome layers.",
      "Build the same quiet uniform with a Vérane blazer, a SÀNSO tote, and a minimal sneaker.",
    ],
  },
  {
    slug: "care-for-leather-cashmere",
    title: "Product Care: Leather, Cashmere & Silk",
    dek: "A practical guide to keeping investment pieces beautiful for decades.",
    category: "Product Care",
    author: "Sofie Lund",
    readTime: 5,
    date: "2026-06-28",
    hero: "journal-sustainability",
    productIds: ["structured-leather-tote", "cashmere-travel-wrap", "fluid-silk-slip-dress"],
    body: [
      "Care is part of luxury. Leather wants a dry cloth and occasional conditioning; cashmere prefers a gentle hand wash and flat dry; silk asks for cool water and shade.",
      "Store structured bags stuffed, not crushed. Fold knits; never hang them. Keep silk away from direct sun.",
      "When in doubt, our clothing-care membership includes steam, minor repairs, and seasonal storage credits.",
    ],
  },
];

export function getArticle(slug: string) {
  return journal.find((a) => a.slug === slug);
}

export function articlesByCategory(category?: string) {
  if (!category || category === "All") return journal;
  return journal.filter((a) => a.category === category);
}

export function articlesForBrand(brandId: string) {
  return journal.filter((a) => a.brandId === brandId);
}
